### ISSUE TITLE
Converting fails with this scratch project

### ISSUE THREAD

**Issue by Mrmayman** [aspizu/sb2gs#9]
[mc10-gen1.sb3.zip](https://github.com/aspizu/sb2gs/files/11414323/mc10-gen1.sb3.zip)
Extract this zip file and you will get an sb3 project. When I try to convert it with sb2gs, it produces the following error
```
$ python sb2gs mc10-gen1.sb3 mc10
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/__main__.py", line 33, in <module>
    main()
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/__main__.py", line 30, in main
    Builder(input, output)
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/builder.py", line 22, in __init__
    self.build_project(json.load(sb3.open("project.json")))
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/builder.py", line 31, in build_project
    self.build_sprite(sprite)
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/builder.py", line 44, in build_sprite
    CodeGen(out, sprite, self.globals, self.listglobals)
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/codegen.py", line 64, in __init__
    self.block(block)
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/codegen.py", line 159, in block
    self.control_forever(o)
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/codegen.py", line 315, in control_forever
    self.block(self.blocks[o["inputs"]["SUBSTACK"][1]])
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/codegen.py", line 151, in block
    self.control_if(o)
  File "/home/mrmayman/Documents/Programs/sb2gs-main/sb2gs/codegen.py", line 291, in control_if
    self.input(o["inputs"]["CONDITION"])
KeyError: 'CONDITION'
```

When i check the converted folder (mc10), the assets are there, and gs files are there. But when I open the gs file with a text editor it looks like it was cut off halfway

![image](https://user-images.githubusercontent.com/119435518/236667305-2d22fb36-db1e-4e49-998b-c111fadeb2b1.png)

Not sure if I'm being dumb here. I understand this is a very hard thing to code (i myself made something like sb2gs but gave up). Hope you are able to solve this!

**Comment by aspizu** [comment]
> I understand this is a very hard thing to code
It's not, really. The way this works is actually quite simple, you traverse the Abstract Syntax Tree from top to bottom and generate text depending on what the nodes are.

The reason it cuts half way is because that is the location where the error occured. While traversing the AST generated code is instantly written into the output files.

The reason this error is occuring is because you have a IF block which does not have a condition inside it. When I wrote the code, I did not account for this so just add a NOT block as the condition.

**Comment by Mrmayman** [comment]
Wow that worked. Thank you so much for the help!
